import type { Category } from '../../store/useBudgetStore';

export interface KeywordTarget {
  category: Category;
  subcategory: string;
}

// Seed dictionary: lowercase keyword → target category + subcategory.
// Subcategories intentionally map onto the existing SUBCATEGORIES lists so the
// override chips always have a matching entry. Learned corrections (SQLite)
// take precedence over these at detection time — see lib/detectCategory.ts.
export const EN_KEYWORDS: Record<string, KeywordTarget> = {
  // ─── needs · Groceries ──────────────────────────────────────────────
  groceries: { category: 'needs', subcategory: 'Groceries' },
  grocery: { category: 'needs', subcategory: 'Groceries' },
  supermarket: { category: 'needs', subcategory: 'Groceries' },
  market: { category: 'needs', subcategory: 'Groceries' },
  minimarket: { category: 'needs', subcategory: 'Groceries' },
  bodega: { category: 'needs', subcategory: 'Groceries' },
  butcher: { category: 'needs', subcategory: 'Groceries' },
  bakery: { category: 'needs', subcategory: 'Groceries' },
  produce: { category: 'needs', subcategory: 'Groceries' },
  aldi: { category: 'needs', subcategory: 'Groceries' },
  lidl: { category: 'needs', subcategory: 'Groceries' },
  walmart: { category: 'needs', subcategory: 'Groceries' },
  costco: { category: 'needs', subcategory: 'Groceries' },
  target: { category: 'needs', subcategory: 'Groceries' },
  kroger: { category: 'needs', subcategory: 'Groceries' },
  safeway: { category: 'needs', subcategory: 'Groceries' },
  publix: { category: 'needs', subcategory: 'Groceries' },
  wholefoods: { category: 'needs', subcategory: 'Groceries' },
  traderjoes: { category: 'needs', subcategory: 'Groceries' },
  tesco: { category: 'needs', subcategory: 'Groceries' },
  sainsburys: { category: 'needs', subcategory: 'Groceries' },
  asda: { category: 'needs', subcategory: 'Groceries' },
  morrisons: { category: 'needs', subcategory: 'Groceries' },
  waitrose: { category: 'needs', subcategory: 'Groceries' },
  carrefour: { category: 'needs', subcategory: 'Groceries' },
  auchan: { category: 'needs', subcategory: 'Groceries' },
  monoprix: { category: 'needs', subcategory: 'Groceries' },
  rewe: { category: 'needs', subcategory: 'Groceries' },
  edeka: { category: 'needs', subcategory: 'Groceries' },
  spar: { category: 'needs', subcategory: 'Groceries' },
  ica: { category: 'needs', subcategory: 'Groceries' },
  coop: { category: 'needs', subcategory: 'Groceries' },
  woolworths: { category: 'needs', subcategory: 'Groceries' },
  coles: { category: 'needs', subcategory: 'Groceries' },
  foodbasics: { category: 'needs', subcategory: 'Groceries' },
  food: { category: 'needs', subcategory: 'Groceries' },
  fruit: { category: 'needs', subcategory: 'Groceries' },
  vegetables: { category: 'needs', subcategory: 'Groceries' },
  veggies: { category: 'needs', subcategory: 'Groceries' },
  meat: { category: 'needs', subcategory: 'Groceries' },
  milk: { category: 'needs', subcategory: 'Groceries' },
  eggs: { category: 'needs', subcategory: 'Groceries' },
  bread: { category: 'needs', subcategory: 'Groceries' },

  // ─── needs · Transport ──────────────────────────────────────────────
  uber: { category: 'needs', subcategory: 'Transport' },
  lyft: { category: 'needs', subcategory: 'Transport' },
  bolt: { category: 'needs', subcategory: 'Transport' },
  grab: { category: 'needs', subcategory: 'Transport' },
  didi: { category: 'needs', subcategory: 'Transport' },
  ola: { category: 'needs', subcategory: 'Transport' },
  taxi: { category: 'needs', subcategory: 'Transport' },
  cab: { category: 'needs', subcategory: 'Transport' },
  rideshare: { category: 'needs', subcategory: 'Transport' },
  bus: { category: 'needs', subcategory: 'Transport' },
  metro: { category: 'needs', subcategory: 'Transport' },
  tram: { category: 'needs', subcategory: 'Transport' },
  train: { category: 'needs', subcategory: 'Transport' },
  rail: { category: 'needs', subcategory: 'Transport' },
  subway: { category: 'needs', subcategory: 'Transport' },
  ferry: { category: 'needs', subcategory: 'Transport' },
  tube: { category: 'needs', subcategory: 'Transport' },
  fuel: { category: 'needs', subcategory: 'Transport' },
  gas: { category: 'needs', subcategory: 'Transport' },
  gasoline: { category: 'needs', subcategory: 'Transport' },
  petrol: { category: 'needs', subcategory: 'Transport' },
  diesel: { category: 'needs', subcategory: 'Transport' },
  parking: { category: 'needs', subcategory: 'Transport' },
  toll: { category: 'needs', subcategory: 'Transport' },
  tolls: { category: 'needs', subcategory: 'Transport' },
  carwash: { category: 'needs', subcategory: 'Transport' },
  mechanic: { category: 'needs', subcategory: 'Transport' },
  carrepair: { category: 'needs', subcategory: 'Transport' },
  tires: { category: 'needs', subcategory: 'Transport' },
  carinsurance: { category: 'needs', subcategory: 'Transport' },
  bike: { category: 'needs', subcategory: 'Transport' },
  scooter: { category: 'needs', subcategory: 'Transport' },
  ticket: { category: 'needs', subcategory: 'Transport' },
  commute: { category: 'needs', subcategory: 'Transport' },

  // ─── needs · Rent ───────────────────────────────────────────────────
  rent: { category: 'needs', subcategory: 'Rent' },
  mortgage: { category: 'needs', subcategory: 'Rent' },
  landlord: { category: 'needs', subcategory: 'Rent' },
  lease: { category: 'needs', subcategory: 'Rent' },
  hoa: { category: 'needs', subcategory: 'Rent' },
  maintenance: { category: 'needs', subcategory: 'Rent' },
  deposit: { category: 'needs', subcategory: 'Rent' },

  // ─── needs · Bills ──────────────────────────────────────────────────
  bill: { category: 'needs', subcategory: 'Bills' },
  bills: { category: 'needs', subcategory: 'Bills' },
  utilities: { category: 'needs', subcategory: 'Bills' },
  electricity: { category: 'needs', subcategory: 'Bills' },
  electric: { category: 'needs', subcategory: 'Bills' },
  power: { category: 'needs', subcategory: 'Bills' },
  water: { category: 'needs', subcategory: 'Bills' },
  gasbill: { category: 'needs', subcategory: 'Bills' },
  heating: { category: 'needs', subcategory: 'Bills' },
  internet: { category: 'needs', subcategory: 'Bills' },
  broadband: { category: 'needs', subcategory: 'Bills' },
  wifi: { category: 'needs', subcategory: 'Bills' },
  phone: { category: 'needs', subcategory: 'Bills' },
  mobile: { category: 'needs', subcategory: 'Bills' },
  cellphone: { category: 'needs', subcategory: 'Bills' },
  verizon: { category: 'needs', subcategory: 'Bills' },
  att: { category: 'needs', subcategory: 'Bills' },
  tmobile: { category: 'needs', subcategory: 'Bills' },
  vodafone: { category: 'needs', subcategory: 'Bills' },
  orange: { category: 'needs', subcategory: 'Bills' },
  insurance: { category: 'needs', subcategory: 'Bills' },
  trash: { category: 'needs', subcategory: 'Bills' },
  sewage: { category: 'needs', subcategory: 'Bills' },
  counciltax: { category: 'needs', subcategory: 'Bills' },
  tax: { category: 'needs', subcategory: 'Bills' },
  taxes: { category: 'needs', subcategory: 'Bills' },

  // ─── needs · Health ─────────────────────────────────────────────────
  pharmacy: { category: 'needs', subcategory: 'Health' },
  drugstore: { category: 'needs', subcategory: 'Health' },
  cvs: { category: 'needs', subcategory: 'Health' },
  walgreens: { category: 'needs', subcategory: 'Health' },
  boots: { category: 'needs', subcategory: 'Health' },
  doctor: { category: 'needs', subcategory: 'Health' },
  physician: { category: 'needs', subcategory: 'Health' },
  clinic: { category: 'needs', subcategory: 'Health' },
  hospital: { category: 'needs', subcategory: 'Health' },
  dentist: { category: 'needs', subcategory: 'Health' },
  dental: { category: 'needs', subcategory: 'Health' },
  optician: { category: 'needs', subcategory: 'Health' },
  optometrist: { category: 'needs', subcategory: 'Health' },
  glasses: { category: 'needs', subcategory: 'Health' },
  contacts: { category: 'needs', subcategory: 'Health' },
  medicine: { category: 'needs', subcategory: 'Health' },
  medication: { category: 'needs', subcategory: 'Health' },
  prescription: { category: 'needs', subcategory: 'Health' },
  vitamins: { category: 'needs', subcategory: 'Health' },
  therapy: { category: 'needs', subcategory: 'Health' },
  therapist: { category: 'needs', subcategory: 'Health' },
  counseling: { category: 'needs', subcategory: 'Health' },
  gym: { category: 'needs', subcategory: 'Health' },
  fitness: { category: 'needs', subcategory: 'Health' },
  yoga: { category: 'needs', subcategory: 'Health' },
  physio: { category: 'needs', subcategory: 'Health' },
  chiropractor: { category: 'needs', subcategory: 'Health' },
  checkup: { category: 'needs', subcategory: 'Health' },

  // ─── needs · Education ──────────────────────────────────────────────
  book: { category: 'needs', subcategory: 'Education' },
  books: { category: 'needs', subcategory: 'Education' },
  textbook: { category: 'needs', subcategory: 'Education' },
  textbooks: { category: 'needs', subcategory: 'Education' },
  course: { category: 'needs', subcategory: 'Education' },
  class: { category: 'needs', subcategory: 'Education' },
  tuition: { category: 'needs', subcategory: 'Education' },
  school: { category: 'needs', subcategory: 'Education' },
  university: { category: 'needs', subcategory: 'Education' },
  college: { category: 'needs', subcategory: 'Education' },
  studentloan: { category: 'needs', subcategory: 'Education' },
  supplies: { category: 'needs', subcategory: 'Education' },
  udemy: { category: 'needs', subcategory: 'Education' },
  coursera: { category: 'needs', subcategory: 'Education' },
  workshop: { category: 'needs', subcategory: 'Education' },
  daycare: { category: 'needs', subcategory: 'Education' },
  childcare: { category: 'needs', subcategory: 'Education' },

  // ─── wants · Dining ─────────────────────────────────────────────────
  coffee: { category: 'wants', subcategory: 'Dining' },
  starbucks: { category: 'wants', subcategory: 'Dining' },
  costa: { category: 'wants', subcategory: 'Dining' },
  latte: { category: 'wants', subcategory: 'Dining' },
  cappuccino: { category: 'wants', subcategory: 'Dining' },
  espresso: { category: 'wants', subcategory: 'Dining' },
  tea: { category: 'wants', subcategory: 'Dining' },
  bubbletea: { category: 'wants', subcategory: 'Dining' },
  juice: { category: 'wants', subcategory: 'Dining' },
  smoothie: { category: 'wants', subcategory: 'Dining' },
  restaurant: { category: 'wants', subcategory: 'Dining' },
  diner: { category: 'wants', subcategory: 'Dining' },
  cafe: { category: 'wants', subcategory: 'Dining' },
  bistro: { category: 'wants', subcategory: 'Dining' },
  lunch: { category: 'wants', subcategory: 'Dining' },
  dinner: { category: 'wants', subcategory: 'Dining' },
  breakfast: { category: 'wants', subcategory: 'Dining' },
  brunch: { category: 'wants', subcategory: 'Dining' },
  takeout: { category: 'wants', subcategory: 'Dining' },
  takeaway: { category: 'wants', subcategory: 'Dining' },
  delivery: { category: 'wants', subcategory: 'Dining' },
  ubereats: { category: 'wants', subcategory: 'Dining' },
  doordash: { category: 'wants', subcategory: 'Dining' },
  deliveroo: { category: 'wants', subcategory: 'Dining' },
  grubhub: { category: 'wants', subcategory: 'Dining' },
  postmates: { category: 'wants', subcategory: 'Dining' },
  justeat: { category: 'wants', subcategory: 'Dining' },
  pizza: { category: 'wants', subcategory: 'Dining' },
  dominos: { category: 'wants', subcategory: 'Dining' },
  pizzahut: { category: 'wants', subcategory: 'Dining' },
  burger: { category: 'wants', subcategory: 'Dining' },
  mcdonalds: { category: 'wants', subcategory: 'Dining' },
  kfc: { category: 'wants', subcategory: 'Dining' },
  burgerking: { category: 'wants', subcategory: 'Dining' },
  wendys: { category: 'wants', subcategory: 'Dining' },
  chipotle: { category: 'wants', subcategory: 'Dining' },
  sushi: { category: 'wants', subcategory: 'Dining' },
  ramen: { category: 'wants', subcategory: 'Dining' },
  noodles: { category: 'wants', subcategory: 'Dining' },
  curry: { category: 'wants', subcategory: 'Dining' },
  kebab: { category: 'wants', subcategory: 'Dining' },
  taco: { category: 'wants', subcategory: 'Dining' },
  tacos: { category: 'wants', subcategory: 'Dining' },
  bbq: { category: 'wants', subcategory: 'Dining' },
  buffet: { category: 'wants', subcategory: 'Dining' },
  dessert: { category: 'wants', subcategory: 'Dining' },
  icecream: { category: 'wants', subcategory: 'Dining' },
  cake: { category: 'wants', subcategory: 'Dining' },
  donut: { category: 'wants', subcategory: 'Dining' },
  donuts: { category: 'wants', subcategory: 'Dining' },
  bagel: { category: 'wants', subcategory: 'Dining' },
  beer: { category: 'wants', subcategory: 'Dining' },
  wine: { category: 'wants', subcategory: 'Dining' },
  cocktail: { category: 'wants', subcategory: 'Dining' },
  cocktails: { category: 'wants', subcategory: 'Dining' },
  bar: { category: 'wants', subcategory: 'Dining' },
  pub: { category: 'wants', subcategory: 'Dining' },
  club: { category: 'wants', subcategory: 'Dining' },
  snack: { category: 'wants', subcategory: 'Dining' },
  snacks: { category: 'wants', subcategory: 'Dining' },

  // ─── wants · Entertainment ──────────────────────────────────────────
  movie: { category: 'wants', subcategory: 'Entertainment' },
  movies: { category: 'wants', subcategory: 'Entertainment' },
  cinema: { category: 'wants', subcategory: 'Entertainment' },
  theatre: { category: 'wants', subcategory: 'Entertainment' },
  theater: { category: 'wants', subcategory: 'Entertainment' },
  museum: { category: 'wants', subcategory: 'Entertainment' },
  gallery: { category: 'wants', subcategory: 'Entertainment' },
  zoo: { category: 'wants', subcategory: 'Entertainment' },
  aquarium: { category: 'wants', subcategory: 'Entertainment' },
  amusementpark: { category: 'wants', subcategory: 'Entertainment' },
  bowling: { category: 'wants', subcategory: 'Entertainment' },
  arcade: { category: 'wants', subcategory: 'Entertainment' },
  karaoke: { category: 'wants', subcategory: 'Entertainment' },
  game: { category: 'wants', subcategory: 'Entertainment' },
  games: { category: 'wants', subcategory: 'Entertainment' },
  gaming: { category: 'wants', subcategory: 'Entertainment' },
  steam: { category: 'wants', subcategory: 'Entertainment' },
  playstation: { category: 'wants', subcategory: 'Entertainment' },
  xbox: { category: 'wants', subcategory: 'Entertainment' },
  nintendo: { category: 'wants', subcategory: 'Entertainment' },
  concert: { category: 'wants', subcategory: 'Entertainment' },
  festival: { category: 'wants', subcategory: 'Entertainment' },
  show: { category: 'wants', subcategory: 'Entertainment' },
  tickets: { category: 'wants', subcategory: 'Entertainment' },
  eventbrite: { category: 'wants', subcategory: 'Entertainment' },
  ticketmaster: { category: 'wants', subcategory: 'Entertainment' },

  // ─── wants · Shopping ───────────────────────────────────────────────
  clothes: { category: 'wants', subcategory: 'Shopping' },
  clothing: { category: 'wants', subcategory: 'Shopping' },
  shoes: { category: 'wants', subcategory: 'Shopping' },
  sneakers: { category: 'wants', subcategory: 'Shopping' },
  jacket: { category: 'wants', subcategory: 'Shopping' },
  jeans: { category: 'wants', subcategory: 'Shopping' },
  dress: { category: 'wants', subcategory: 'Shopping' },
  bag: { category: 'wants', subcategory: 'Shopping' },
  handbag: { category: 'wants', subcategory: 'Shopping' },
  jewelry: { category: 'wants', subcategory: 'Shopping' },
  jewellery: { category: 'wants', subcategory: 'Shopping' },
  watch: { category: 'wants', subcategory: 'Shopping' },
  makeup: { category: 'wants', subcategory: 'Shopping' },
  cosmetics: { category: 'wants', subcategory: 'Shopping' },
  perfume: { category: 'wants', subcategory: 'Shopping' },
  amazon: { category: 'wants', subcategory: 'Shopping' },
  ebay: { category: 'wants', subcategory: 'Shopping' },
  etsy: { category: 'wants', subcategory: 'Shopping' },
  aliexpress: { category: 'wants', subcategory: 'Shopping' },
  shein: { category: 'wants', subcategory: 'Shopping' },
  zara: { category: 'wants', subcategory: 'Shopping' },
  hm: { category: 'wants', subcategory: 'Shopping' },
  uniqlo: { category: 'wants', subcategory: 'Shopping' },
  nike: { category: 'wants', subcategory: 'Shopping' },
  adidas: { category: 'wants', subcategory: 'Shopping' },
  ikea: { category: 'wants', subcategory: 'Shopping' },
  homegoods: { category: 'wants', subcategory: 'Shopping' },
  furniture: { category: 'wants', subcategory: 'Shopping' },
  decor: { category: 'wants', subcategory: 'Shopping' },
  electronics: { category: 'wants', subcategory: 'Shopping' },
  gadget: { category: 'wants', subcategory: 'Shopping' },
  gadgets: { category: 'wants', subcategory: 'Shopping' },
  phonecase: { category: 'wants', subcategory: 'Shopping' },
  headphones: { category: 'wants', subcategory: 'Shopping' },
  laptop: { category: 'wants', subcategory: 'Shopping' },
  gift: { category: 'wants', subcategory: 'Shopping' },
  gifts: { category: 'wants', subcategory: 'Shopping' },
  present: { category: 'wants', subcategory: 'Shopping' },
  toy: { category: 'wants', subcategory: 'Shopping' },
  toys: { category: 'wants', subcategory: 'Shopping' },
  shopping: { category: 'wants', subcategory: 'Shopping' },
  mall: { category: 'wants', subcategory: 'Shopping' },

  // ─── wants · Travel ─────────────────────────────────────────────────
  flight: { category: 'wants', subcategory: 'Travel' },
  flights: { category: 'wants', subcategory: 'Travel' },
  airline: { category: 'wants', subcategory: 'Travel' },
  airbnb: { category: 'wants', subcategory: 'Travel' },
  hotel: { category: 'wants', subcategory: 'Travel' },
  motel: { category: 'wants', subcategory: 'Travel' },
  hostel: { category: 'wants', subcategory: 'Travel' },
  resort: { category: 'wants', subcategory: 'Travel' },
  booking: { category: 'wants', subcategory: 'Travel' },
  expedia: { category: 'wants', subcategory: 'Travel' },
  trip: { category: 'wants', subcategory: 'Travel' },
  vacation: { category: 'wants', subcategory: 'Travel' },
  holiday: { category: 'wants', subcategory: 'Travel' },
  cruise: { category: 'wants', subcategory: 'Travel' },
  rentalcar: { category: 'wants', subcategory: 'Travel' },
  hertz: { category: 'wants', subcategory: 'Travel' },
  avis: { category: 'wants', subcategory: 'Travel' },
  luggage: { category: 'wants', subcategory: 'Travel' },
  suitcase: { category: 'wants', subcategory: 'Travel' },
  visa: { category: 'wants', subcategory: 'Travel' },
  passport: { category: 'wants', subcategory: 'Travel' },
  souvenir: { category: 'wants', subcategory: 'Travel' },
  souvenirs: { category: 'wants', subcategory: 'Travel' },

  // ─── wants · Subscriptions ──────────────────────────────────────────
  netflix: { category: 'wants', subcategory: 'Subscriptions' },
  spotify: { category: 'wants', subcategory: 'Subscriptions' },
  subscription: { category: 'wants', subcategory: 'Subscriptions' },
  subscriptions: { category: 'wants', subcategory: 'Subscriptions' },
  youtube: { category: 'wants', subcategory: 'Subscriptions' },
  hulu: { category: 'wants', subcategory: 'Subscriptions' },
  disneyplus: { category: 'wants', subcategory: 'Subscriptions' },
  hbomax: { category: 'wants', subcategory: 'Subscriptions' },
  primevideo: { category: 'wants', subcategory: 'Subscriptions' },
  appletv: { category: 'wants', subcategory: 'Subscriptions' },
  applemusic: { category: 'wants', subcategory: 'Subscriptions' },
  audible: { category: 'wants', subcategory: 'Subscriptions' },
  kindle: { category: 'wants', subcategory: 'Subscriptions' },
  icloud: { category: 'wants', subcategory: 'Subscriptions' },
  dropbox: { category: 'wants', subcategory: 'Subscriptions' },
  patreon: { category: 'wants', subcategory: 'Subscriptions' },
  chatgpt: { category: 'wants', subcategory: 'Subscriptions' },
  software: { category: 'wants', subcategory: 'Subscriptions' },
  app: { category: 'wants', subcategory: 'Subscriptions' },

  // ─── savings · Emergency Fund ───────────────────────────────────────
  emergency: { category: 'savings', subcategory: 'Emergency Fund' },
  savings: { category: 'savings', subcategory: 'Emergency Fund' },
  rainyday: { category: 'savings', subcategory: 'Emergency Fund' },
  cushion: { category: 'savings', subcategory: 'Emergency Fund' },

  // ─── savings · Investment ───────────────────────────────────────────
  investment: { category: 'savings', subcategory: 'Investment' },
  investing: { category: 'savings', subcategory: 'Investment' },
  stocks: { category: 'savings', subcategory: 'Investment' },
  shares: { category: 'savings', subcategory: 'Investment' },
  etf: { category: 'savings', subcategory: 'Investment' },
  index: { category: 'savings', subcategory: 'Investment' },
  bonds: { category: 'savings', subcategory: 'Investment' },
  crypto: { category: 'savings', subcategory: 'Investment' },
  bitcoin: { category: 'savings', subcategory: 'Investment' },
  ethereum: { category: 'savings', subcategory: 'Investment' },
  brokerage: { category: 'savings', subcategory: 'Investment' },

  // ─── savings · Retirement ───────────────────────────────────────────
  retirement: { category: 'savings', subcategory: 'Retirement' },
  pension: { category: 'savings', subcategory: 'Retirement' },
  '401k': { category: 'savings', subcategory: 'Retirement' },
  ira: { category: 'savings', subcategory: 'Retirement' },
  roth: { category: 'savings', subcategory: 'Retirement' },

  // ─── savings · Goal ─────────────────────────────────────────────────
  goal: { category: 'savings', subcategory: 'Goal' },
  wedding: { category: 'savings', subcategory: 'Goal' },
  downpayment: { category: 'savings', subcategory: 'Goal' },
};
