import type { Category } from '../../store/useBudgetStore';
import type { KeywordTarget } from './en';

// French seed dictionary: lowercase keyword → target category + subcategory.
// Subcategory values intentionally stay the same English strings as
// constants/subcategories.ts (not translated) so the override chips always
// match, mirroring en.ts. Learned corrections (SQLite) take precedence over
// these at detection time — see lib/detectCategory.ts.
export const FR_KEYWORDS: Record<string, KeywordTarget> = {
  // ─── needs · Groceries ──────────────────────────────────────────────
  courses: { category: 'needs', subcategory: 'Groceries' },
  epicerie: { category: 'needs', subcategory: 'Groceries' },
  supermarche: { category: 'needs', subcategory: 'Groceries' },
  marche: { category: 'needs', subcategory: 'Groceries' },
  boucherie: { category: 'needs', subcategory: 'Groceries' },
  boucher: { category: 'needs', subcategory: 'Groceries' },
  boulangerie: { category: 'needs', subcategory: 'Groceries' },
  boulanger: { category: 'needs', subcategory: 'Groceries' },
  patisserie: { category: 'needs', subcategory: 'Groceries' },
  primeur: { category: 'needs', subcategory: 'Groceries' },
  carrefour: { category: 'needs', subcategory: 'Groceries' },
  auchan: { category: 'needs', subcategory: 'Groceries' },
  monoprix: { category: 'needs', subcategory: 'Groceries' },
  leclerc: { category: 'needs', subcategory: 'Groceries' },
  intermarche: { category: 'needs', subcategory: 'Groceries' },
  casino: { category: 'needs', subcategory: 'Groceries' },
  franprix: { category: 'needs', subcategory: 'Groceries' },
  lidl: { category: 'needs', subcategory: 'Groceries' },
  aldi: { category: 'needs', subcategory: 'Groceries' },
  picard: { category: 'needs', subcategory: 'Groceries' },
  nourriture: { category: 'needs', subcategory: 'Groceries' },
  fruits: { category: 'needs', subcategory: 'Groceries' },
  legumes: { category: 'needs', subcategory: 'Groceries' },
  viande: { category: 'needs', subcategory: 'Groceries' },
  poisson: { category: 'needs', subcategory: 'Groceries' },
  lait: { category: 'needs', subcategory: 'Groceries' },
  oeufs: { category: 'needs', subcategory: 'Groceries' },
  pain: { category: 'needs', subcategory: 'Groceries' },
  fromage: { category: 'needs', subcategory: 'Groceries' },

  // ─── needs · Transport ──────────────────────────────────────────────
  uber: { category: 'needs', subcategory: 'Transport' },
  bolt: { category: 'needs', subcategory: 'Transport' },
  taxi: { category: 'needs', subcategory: 'Transport' },
  bus: { category: 'needs', subcategory: 'Transport' },
  metro: { category: 'needs', subcategory: 'Transport' },
  tram: { category: 'needs', subcategory: 'Transport' },
  tramway: { category: 'needs', subcategory: 'Transport' },
  train: { category: 'needs', subcategory: 'Transport' },
  sncf: { category: 'needs', subcategory: 'Transport' },
  ratp: { category: 'needs', subcategory: 'Transport' },
  navigo: { category: 'needs', subcategory: 'Transport' },
  ferry: { category: 'needs', subcategory: 'Transport' },
  essence: { category: 'needs', subcategory: 'Transport' },
  carburant: { category: 'needs', subcategory: 'Transport' },
  gasoil: { category: 'needs', subcategory: 'Transport' },
  diesel: { category: 'needs', subcategory: 'Transport' },
  parking: { category: 'needs', subcategory: 'Transport' },
  peage: { category: 'needs', subcategory: 'Transport' },
  lavage: { category: 'needs', subcategory: 'Transport' },
  garagiste: { category: 'needs', subcategory: 'Transport' },
  garage: { category: 'needs', subcategory: 'Transport' },
  reparation: { category: 'needs', subcategory: 'Transport' },
  pneus: { category: 'needs', subcategory: 'Transport' },
  assurancevoiture: { category: 'needs', subcategory: 'Transport' },
  velo: { category: 'needs', subcategory: 'Transport' },
  trottinette: { category: 'needs', subcategory: 'Transport' },
  billet: { category: 'needs', subcategory: 'Transport' },
  trajet: { category: 'needs', subcategory: 'Transport' },

  // ─── needs · Rent ───────────────────────────────────────────────────
  loyer: { category: 'needs', subcategory: 'Rent' },
  bailleur: { category: 'needs', subcategory: 'Rent' },
  proprietaire: { category: 'needs', subcategory: 'Rent' },
  bail: { category: 'needs', subcategory: 'Rent' },
  charges: { category: 'needs', subcategory: 'Rent' },
  copropriete: { category: 'needs', subcategory: 'Rent' },
  entretien: { category: 'needs', subcategory: 'Rent' },
  caution: { category: 'needs', subcategory: 'Rent' },
  hypotheque: { category: 'needs', subcategory: 'Rent' },

  // ─── needs · Bills ──────────────────────────────────────────────────
  facture: { category: 'needs', subcategory: 'Bills' },
  factures: { category: 'needs', subcategory: 'Bills' },
  electricite: { category: 'needs', subcategory: 'Bills' },
  edf: { category: 'needs', subcategory: 'Bills' },
  eau: { category: 'needs', subcategory: 'Bills' },
  gaz: { category: 'needs', subcategory: 'Bills' },
  chauffage: { category: 'needs', subcategory: 'Bills' },
  internet: { category: 'needs', subcategory: 'Bills' },
  wifi: { category: 'needs', subcategory: 'Bills' },
  telephone: { category: 'needs', subcategory: 'Bills' },
  mobile: { category: 'needs', subcategory: 'Bills' },
  orange: { category: 'needs', subcategory: 'Bills' },
  sfr: { category: 'needs', subcategory: 'Bills' },
  bouygues: { category: 'needs', subcategory: 'Bills' },
  free: { category: 'needs', subcategory: 'Bills' },
  assurance: { category: 'needs', subcategory: 'Bills' },
  ordures: { category: 'needs', subcategory: 'Bills' },
  impots: { category: 'needs', subcategory: 'Bills' },
  taxe: { category: 'needs', subcategory: 'Bills' },
  taxes: { category: 'needs', subcategory: 'Bills' },

  // ─── needs · Health ─────────────────────────────────────────────────
  pharmacie: { category: 'needs', subcategory: 'Health' },
  medecin: { category: 'needs', subcategory: 'Health' },
  docteur: { category: 'needs', subcategory: 'Health' },
  clinique: { category: 'needs', subcategory: 'Health' },
  hopital: { category: 'needs', subcategory: 'Health' },
  dentiste: { category: 'needs', subcategory: 'Health' },
  opticien: { category: 'needs', subcategory: 'Health' },
  lunettes: { category: 'needs', subcategory: 'Health' },
  lentilles: { category: 'needs', subcategory: 'Health' },
  medicament: { category: 'needs', subcategory: 'Health' },
  medicaments: { category: 'needs', subcategory: 'Health' },
  ordonnance: { category: 'needs', subcategory: 'Health' },
  vitamines: { category: 'needs', subcategory: 'Health' },
  therapie: { category: 'needs', subcategory: 'Health' },
  psychologue: { category: 'needs', subcategory: 'Health' },
  salle: { category: 'needs', subcategory: 'Health' },
  fitness: { category: 'needs', subcategory: 'Health' },
  yoga: { category: 'needs', subcategory: 'Health' },
  kine: { category: 'needs', subcategory: 'Health' },
  osteopathe: { category: 'needs', subcategory: 'Health' },
  checkup: { category: 'needs', subcategory: 'Health' },

  // ─── needs · Education ──────────────────────────────────────────────
  livre: { category: 'needs', subcategory: 'Education' },
  livres: { category: 'needs', subcategory: 'Education' },
  manuel: { category: 'needs', subcategory: 'Education' },
  cours: { category: 'needs', subcategory: 'Education' },
  formation: { category: 'needs', subcategory: 'Education' },
  scolarite: { category: 'needs', subcategory: 'Education' },
  ecole: { category: 'needs', subcategory: 'Education' },
  universite: { category: 'needs', subcategory: 'Education' },
  fac: { category: 'needs', subcategory: 'Education' },
  pretetudiant: { category: 'needs', subcategory: 'Education' },
  fournitures: { category: 'needs', subcategory: 'Education' },
  atelier: { category: 'needs', subcategory: 'Education' },
  creche: { category: 'needs', subcategory: 'Education' },
  garderie: { category: 'needs', subcategory: 'Education' },
  nourrice: { category: 'needs', subcategory: 'Education' },

  // ─── wants · Dining ─────────────────────────────────────────────────
  cafe: { category: 'wants', subcategory: 'Dining' },
  cafes: { category: 'wants', subcategory: 'Dining' },
  the: { category: 'wants', subcategory: 'Dining' },
  jus: { category: 'wants', subcategory: 'Dining' },
  restaurant: { category: 'wants', subcategory: 'Dining' },
  brasserie: { category: 'wants', subcategory: 'Dining' },
  bistro: { category: 'wants', subcategory: 'Dining' },
  bistrot: { category: 'wants', subcategory: 'Dining' },
  dejeuner: { category: 'wants', subcategory: 'Dining' },
  diner: { category: 'wants', subcategory: 'Dining' },
  petitdejeuner: { category: 'wants', subcategory: 'Dining' },
  brunch: { category: 'wants', subcategory: 'Dining' },
  livraison: { category: 'wants', subcategory: 'Dining' },
  ubereats: { category: 'wants', subcategory: 'Dining' },
  deliveroo: { category: 'wants', subcategory: 'Dining' },
  justeat: { category: 'wants', subcategory: 'Dining' },
  pizza: { category: 'wants', subcategory: 'Dining' },
  burger: { category: 'wants', subcategory: 'Dining' },
  mcdonalds: { category: 'wants', subcategory: 'Dining' },
  kfc: { category: 'wants', subcategory: 'Dining' },
  sushi: { category: 'wants', subcategory: 'Dining' },
  kebab: { category: 'wants', subcategory: 'Dining' },
  dessert: { category: 'wants', subcategory: 'Dining' },
  glace: { category: 'wants', subcategory: 'Dining' },
  gateau: { category: 'wants', subcategory: 'Dining' },
  viennoiserie: { category: 'wants', subcategory: 'Dining' },
  biere: { category: 'wants', subcategory: 'Dining' },
  vin: { category: 'wants', subcategory: 'Dining' },
  cocktail: { category: 'wants', subcategory: 'Dining' },
  bar: { category: 'wants', subcategory: 'Dining' },
  pub: { category: 'wants', subcategory: 'Dining' },
  boite: { category: 'wants', subcategory: 'Dining' },
  snack: { category: 'wants', subcategory: 'Dining' },
  friandises: { category: 'wants', subcategory: 'Dining' },

  // ─── wants · Entertainment ──────────────────────────────────────────
  cinema: { category: 'wants', subcategory: 'Entertainment' },
  film: { category: 'wants', subcategory: 'Entertainment' },
  theatre: { category: 'wants', subcategory: 'Entertainment' },
  musee: { category: 'wants', subcategory: 'Entertainment' },
  galerie: { category: 'wants', subcategory: 'Entertainment' },
  zoo: { category: 'wants', subcategory: 'Entertainment' },
  aquarium: { category: 'wants', subcategory: 'Entertainment' },
  parcattractions: { category: 'wants', subcategory: 'Entertainment' },
  bowling: { category: 'wants', subcategory: 'Entertainment' },
  jeu: { category: 'wants', subcategory: 'Entertainment' },
  jeux: { category: 'wants', subcategory: 'Entertainment' },
  jeuvideo: { category: 'wants', subcategory: 'Entertainment' },
  steam: { category: 'wants', subcategory: 'Entertainment' },
  playstation: { category: 'wants', subcategory: 'Entertainment' },
  xbox: { category: 'wants', subcategory: 'Entertainment' },
  nintendo: { category: 'wants', subcategory: 'Entertainment' },
  concert: { category: 'wants', subcategory: 'Entertainment' },
  festival: { category: 'wants', subcategory: 'Entertainment' },
  spectacle: { category: 'wants', subcategory: 'Entertainment' },
  billets: { category: 'wants', subcategory: 'Entertainment' },

  // ─── wants · Shopping ───────────────────────────────────────────────
  vetements: { category: 'wants', subcategory: 'Shopping' },
  chaussures: { category: 'wants', subcategory: 'Shopping' },
  baskets: { category: 'wants', subcategory: 'Shopping' },
  veste: { category: 'wants', subcategory: 'Shopping' },
  jean: { category: 'wants', subcategory: 'Shopping' },
  robe: { category: 'wants', subcategory: 'Shopping' },
  sac: { category: 'wants', subcategory: 'Shopping' },
  bijoux: { category: 'wants', subcategory: 'Shopping' },
  montre: { category: 'wants', subcategory: 'Shopping' },
  maquillage: { category: 'wants', subcategory: 'Shopping' },
  cosmetiques: { category: 'wants', subcategory: 'Shopping' },
  parfum: { category: 'wants', subcategory: 'Shopping' },
  amazon: { category: 'wants', subcategory: 'Shopping' },
  cdiscount: { category: 'wants', subcategory: 'Shopping' },
  fnac: { category: 'wants', subcategory: 'Shopping' },
  zara: { category: 'wants', subcategory: 'Shopping' },
  hm: { category: 'wants', subcategory: 'Shopping' },
  uniqlo: { category: 'wants', subcategory: 'Shopping' },
  nike: { category: 'wants', subcategory: 'Shopping' },
  adidas: { category: 'wants', subcategory: 'Shopping' },
  ikea: { category: 'wants', subcategory: 'Shopping' },
  meubles: { category: 'wants', subcategory: 'Shopping' },
  decoration: { category: 'wants', subcategory: 'Shopping' },
  electronique: { category: 'wants', subcategory: 'Shopping' },
  gadget: { category: 'wants', subcategory: 'Shopping' },
  ecouteurs: { category: 'wants', subcategory: 'Shopping' },
  ordinateur: { category: 'wants', subcategory: 'Shopping' },
  cadeau: { category: 'wants', subcategory: 'Shopping' },
  cadeaux: { category: 'wants', subcategory: 'Shopping' },
  jouet: { category: 'wants', subcategory: 'Shopping' },
  jouets: { category: 'wants', subcategory: 'Shopping' },
  shopping: { category: 'wants', subcategory: 'Shopping' },
  centrecommercial: { category: 'wants', subcategory: 'Shopping' },

  // ─── wants · Travel ─────────────────────────────────────────────────
  vol: { category: 'wants', subcategory: 'Travel' },
  vols: { category: 'wants', subcategory: 'Travel' },
  avion: { category: 'wants', subcategory: 'Travel' },
  airbnb: { category: 'wants', subcategory: 'Travel' },
  hotel: { category: 'wants', subcategory: 'Travel' },
  auberge: { category: 'wants', subcategory: 'Travel' },
  resort: { category: 'wants', subcategory: 'Travel' },
  reservation: { category: 'wants', subcategory: 'Travel' },
  voyage: { category: 'wants', subcategory: 'Travel' },
  vacances: { category: 'wants', subcategory: 'Travel' },
  croisiere: { category: 'wants', subcategory: 'Travel' },
  locationvoiture: { category: 'wants', subcategory: 'Travel' },
  valise: { category: 'wants', subcategory: 'Travel' },
  passeport: { category: 'wants', subcategory: 'Travel' },
  souvenir: { category: 'wants', subcategory: 'Travel' },
  souvenirs: { category: 'wants', subcategory: 'Travel' },

  // ─── wants · Subscriptions ──────────────────────────────────────────
  netflix: { category: 'wants', subcategory: 'Subscriptions' },
  spotify: { category: 'wants', subcategory: 'Subscriptions' },
  abonnement: { category: 'wants', subcategory: 'Subscriptions' },
  abonnements: { category: 'wants', subcategory: 'Subscriptions' },
  youtube: { category: 'wants', subcategory: 'Subscriptions' },
  canalplus: { category: 'wants', subcategory: 'Subscriptions' },
  disneyplus: { category: 'wants', subcategory: 'Subscriptions' },
  primevideo: { category: 'wants', subcategory: 'Subscriptions' },
  appletv: { category: 'wants', subcategory: 'Subscriptions' },
  applemusic: { category: 'wants', subcategory: 'Subscriptions' },
  audible: { category: 'wants', subcategory: 'Subscriptions' },
  kindle: { category: 'wants', subcategory: 'Subscriptions' },
  icloud: { category: 'wants', subcategory: 'Subscriptions' },
  dropbox: { category: 'wants', subcategory: 'Subscriptions' },
  chatgpt: { category: 'wants', subcategory: 'Subscriptions' },
  logiciel: { category: 'wants', subcategory: 'Subscriptions' },
  appli: { category: 'wants', subcategory: 'Subscriptions' },
  application: { category: 'wants', subcategory: 'Subscriptions' },

  // ─── savings · Emergency Fund ───────────────────────────────────────
  urgence: { category: 'savings', subcategory: 'Emergency Fund' },
  epargne: { category: 'savings', subcategory: 'Emergency Fund' },
  epargnes: { category: 'savings', subcategory: 'Emergency Fund' },
  reserve: { category: 'savings', subcategory: 'Emergency Fund' },
  coussin: { category: 'savings', subcategory: 'Emergency Fund' },

  // ─── savings · Investment ───────────────────────────────────────────
  investissement: { category: 'savings', subcategory: 'Investment' },
  investir: { category: 'savings', subcategory: 'Investment' },
  actions: { category: 'savings', subcategory: 'Investment' },
  bourse: { category: 'savings', subcategory: 'Investment' },
  obligations: { category: 'savings', subcategory: 'Investment' },
  crypto: { category: 'savings', subcategory: 'Investment' },
  bitcoin: { category: 'savings', subcategory: 'Investment' },
  ethereum: { category: 'savings', subcategory: 'Investment' },
  courtage: { category: 'savings', subcategory: 'Investment' },

  // ─── savings · Retirement ───────────────────────────────────────────
  retraite: { category: 'savings', subcategory: 'Retirement' },
  pension: { category: 'savings', subcategory: 'Retirement' },
  per: { category: 'savings', subcategory: 'Retirement' },

  // ─── savings · Goal ─────────────────────────────────────────────────
  objectif: { category: 'savings', subcategory: 'Goal' },
  mariage: { category: 'savings', subcategory: 'Goal' },
  apport: { category: 'savings', subcategory: 'Goal' },
};
